package cz.zoom.whiteboard.decoder;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamEvent;
import com.github.sarxos.webcam.WebcamListener;
import com.github.sarxos.webcam.WebcamMotionEvent;
import com.github.sarxos.webcam.WebcamMotionListener;
import com.google.zxing.NotFoundException;
import cz.zoom.whiteboard.task.Task;
import cz.zoom.whiteboard.task.TasksFactory;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class Whiteboard extends javax.swing.JFrame {
    private final WebcamComboboxModel comboModel = new WebcamComboboxModel();
    private Webcam lastWebcam;
    private final WebcamListener webcamListener = new SnapshotListener();
    private final CameraCanvas canvas = new CameraCanvas();
    private final TasksTableModel tasksModel;
    
    private final List<Task> tasks = new ArrayList<Task>();

    private class SnapshotListener implements WebcamListener {

        public void webcamOpen(WebcamEvent we) {
            canvas.setWebcam(we.getSource(), new WebcamMotionListener() {
                public void motionDetected(WebcamMotionEvent wme) {
                    scanTasks();
                }
            });
        }

        private void scanTasks() {
            tasks.clear();
            try {
                Task[] tmpTasks = TasksFactory.createFromImage(canvas.snapshot()).getTasks();
                if (tmpTasks == null) {
                    return;
                }
                tasks.addAll(Arrays.asList(tmpTasks));
                tasksModel.fireTableDataChanged();
            } catch (NotFoundException e) {
                // QR code was not found... ignore
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }

        public void webcamClosed(WebcamEvent we) {
            canvas.setWebcam(null, null);
        }

        public void webcamDisposed(WebcamEvent we) {
        }
    }

    public Whiteboard() throws IOException {
        initComponents();
        setLocationRelativeTo(null);
        comboWebcam.setModel(comboModel);
        cameraPanel.setViewportView(canvas);
        
        tasksModel = new TasksTableModel(tasks);
        tblTasks.setModel(tasksModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        comboWebcam = new javax.swing.JComboBox();
        btnStop = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        cameraPanel = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTasks = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Whiteboard");

        jLabel1.setText("Select device:");

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnStop.setText("Stop");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboWebcam, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 321, Short.MAX_VALUE)
                .addComponent(btnStart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStop)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnStart)
                    .addComponent(comboWebcam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStop))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setDividerLocation(500);

        cameraPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Camera view"));
        jSplitPane1.setLeftComponent(cameraPanel);

        tblTasks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblTasks);

        jSplitPane1.setRightComponent(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSplitPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        if (lastWebcam != null) {
            lastWebcam.close();
            lastWebcam.removeWebcamListener(webcamListener);
            lastWebcam = null;
        }
    }//GEN-LAST:event_btnStopActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        Webcam webcam = (Webcam)comboModel.getSelectedItem();

        if (lastWebcam != webcam) {
            if (lastWebcam != null) {
                lastWebcam.close();
                lastWebcam.removeWebcamListener(webcamListener);
            }
            webcam.addWebcamListener(webcamListener);
            lastWebcam = webcam;
            lastWebcam.open();
        }
    }//GEN-LAST:event_btnStartActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    private javax.swing.JScrollPane cameraPanel;
    private javax.swing.JComboBox comboWebcam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable tblTasks;
    // End of variables declaration//GEN-END:variables
}
