/* --------------------------------------------------------------------- 
//    File:  "kcalc.cpp" 
// 
//    This file was generated by KPI-Yacc 1.00beta.
// 
//    Used specification file: "".
//    Used skeleton file:      "C:\Program Files\PPVP\yaccpar".
// 
//    Created:  Sun Oct 10 06:56:01 2010
// 
--------------------------------------------------------------------- */ 


# line 2 "kcalc.y"
  int yyparse(void), yylex(void);

  typedef struct {
    unsigned char sig;
    int ival;
    double dval;
  } ATRV;

# line 11 "kcalc.y"
typedef union  {
  char* name;
  ATRV attr;
} YYSTYPE;
# define VARIABLE 257
# define INT_VAL 258
# define DBL_VAL 259
# define LPAR 260
# define RPAR 261
# define OP_EQU 262
# define QUIT 263
# define M_SIN 264
# define M_COS 265
# define M_TAN 266
# define M_COTAN 267
# define M_LOG 268
# define M_LOG2 269
# define M_LOGE 270
# define M_SQRT 271
# define M_CEIL 272
# define M_FLOOR 273
# define CONST_PI 274
# define CONST_E 275
# define OP_ADD 276
# define OP_SUB 277
# define OP_MUL 278
# define OP_DIV 279
# define OP_MOD 280
# define UADD 281
# define USUB 282
# define OP_POW 283
# define OP_FACT 284

# line 41 "kcalc.y"

struct { char *name; ATRV attr;} VARIABLES[30];
int var_ix = 0;  // index to new variable

int tmp, ttmp;
double tmp2,ttmp2;

#include <alloc.h>
#include <stdio.h>
#include <string.h>
#include <math.h>


#include "lexyy.cpp"

static int quit = 0;
#define yyclearin yychar = -1
#define yyerrok yyerrflag = 0
extern int yychar;
extern short yyerrflag;
#ifndef YYMAXDEPTH
#define YYMAXDEPTH 150
#endif
YYSTYPE yylval, yyval;
# define YYERRCODE 256

# line 322 "kcalc.y"

/* Functions */

//static int errorCount = 0;

void yyerror(char *s){
  fprintf(stdout,"ERROR: %s [%s]\n",s,yytext);
//  errorCount++;
}

void xxerror(char *s1,char *s2){
  fprintf(stdout,"ERROR: %s %s\n",s1,s2);
//  errorCount++;
}


void initVAR(){
  var_ix = 0;
}

int findVAR(char *name,int errorMissing) {
  int i;
  for(i=0; i < var_ix; i++) {
    if (strcmp(name,VARIABLES[i].name) == 0)
      return i;
  }
  if (errorMissing)
    xxerror("Variable was not defined: ",name);
  return -1;
}

int saveVAR(char *name, ATRV *attr) {
  if (var_ix == 30) {
    xxerror("Variable can not be defined (out of space): ", name);
    return -1;
  }
  VARIABLES[var_ix].name = name;
  memcpy(&VARIABLES[var_ix].attr, attr, sizeof(ATRV));
  var_ix++;
  return var_ix -1;
}

/**
 * Recursively compute a factorial.
 */
int fact(int x) {
  if (x == 0)
    return 1;
  else if (x > 0)
    return x * fact(x-1);
  else
    return -1;
}

void printResult(ATRV *attr) {
  int a = attr->ival;
  double b = attr->dval;
  if (attr->sig == 1)
    printf("\n\t %d\n\tx%X\n",a,a);
  else if (attr->sig == 2)
    printf("\n\t%lf\n",b);
}

int main(int ac,char *av[]){
  extern FILE *yyin;
  int i;
  if(ac>1){
    yyin=fopen(av[1],"r");
    if(yyin==NULL){
      yyin=stdin;
    }
  }
  initVAR();
  
  while(!quit) {
    printf("\n>");
    (void)yyparse();
  }
  return(0);
}

short yyexca[] ={
-1, 1,
	0, -1,
	-2, 0,
	};
# define YYNPROD 32
# define YYLAST 108
short yyact[]={

  17,  20,  21,  19,  28,  30,   3,   5,   6,   7,
   8,   9,  10,  11,  12,  13,  14,  22,  23,  16,
  15,  17,  20,  21,  19,  30,   1,  52,   5,   6,
   7,   8,   9,  10,  11,  12,  13,  14,  22,  23,
  16,  15,  24,  25,  26,  27,  29,  43,  18,  28,
  30,  24,  25,  26,  27,  29,   4,   0,  28,  30,
  26,  27,  29,   2,  29,  28,  30,  28,  30,  31,
  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
  42,   0,   0,  44,   0,   0,   0,   0,  45,  46,
  47,  48,  49,  50,   0,   0,   0,   0,   0,   0,
   0,   0,   0,   0,   0,   0,   0,  51 };
short yypact[]={

-257,-1000,-225,-1000,-1000,-236,-236,-236,-236,-236,
-236,-236,-236,-236,-236,-236,-236,-215,-1000,-236,
-1000,-1000,-1000,-1000,-236,-236,-236,-236,-236,-236,
-1000,-225,-225,-225,-225,-225,-225,-225,-225,-225,
-225,-279,-279,-236,-234,-218,-218,-216,-216,-259,
-279,-225,-1000 };
short yypgo[]={

   0,  63,  56,  48,  26 };
short yyr1[]={

   0,   4,   4,   4,   1,   1,   1,   1,   1,   1,
   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
   1,   1,   1,   1,   2,   2,   2,   2,   3,   3,
   3,   3 };
short yyr2[]={

   0,   0,   1,   1,   1,   3,   3,   3,   3,   3,
   3,   2,   2,   2,   2,   2,   2,   2,   2,   2,
   2,   2,   2,   2,   1,   3,   1,   3,   1,   1,
   1,   1 };
short yychk[]={

-1000,  -4,  -1, 263,  -2, 264, 265, 266, 267, 268,
 269, 270, 271, 272, 273, 277, 276, 257,  -3, 260,
 258, 259, 274, 275, 276, 277, 278, 279, 283, 280,
 284,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
  -1,  -1,  -1, 262,  -1,  -1,  -1,  -1,  -1,  -1,
  -1,  -1, 261 };
short yydef[]={

   1,  -2,   2,   3,   4,   0,   0,   0,   0,   0,
   0,   0,   0,   0,   0,   0,   0,  24,  26,   0,
  28,  29,  30,  31,   0,   0,   0,   0,   0,   0,
  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,
  21,  22,  23,   0,   0,   5,   6,   7,   8,   9,
  10,  25,  27 };

/* ----------------------------------------------------------------------- */
/*             Section copied from skeleton file  "yaccpar"                */
/* ----------------------------------------------------------------------- */

#define   YYFLAG     -1000
#define   YYERROR    goto yyerrlab
#define   YYACCEPT   return ( 0 )
#define   YYABORT    return ( 1 )

/* ---------------------------- */
/*    parser for yacc output    */
/* ---------------------------- */

YYSTYPE   yyv[YYMAXDEPTH];     /* where the values are stored          */
int       yydebug   =  0;      /* Actually OFF,  set '1' for debugging */
int       yychar    = -1;      /* current input token number           */
int       yynerrs   =  0;      /* number of errors                     */
short     yyerrflag =  0;      /* error recovery flag                  */


int  yyparse( void )
{
		  short  int   yys[YYMAXDEPTH];
		  short  int   yyj,
							yym;

		  register  YYSTYPE    *yypvt;
		  register  YYSTYPE    *yypv;

		  register  short  int   *yyxi;
		  register  short  int    yystate,
										 *yyps,
										  yyn;


		  yystate   =   0;
		  yychar    =  -1;
		  yynerrs   =   0;
		  yyerrflag =   0;
		  yyps      = &yys[-1];
		  yypv      = &yyv[-1];

yystack:
		  /* put a state and value onto the stack */

		  if ( yydebug  )
				printf( "state %d, char 0%o\n", yystate, yychar );

		  if ( ++yyps > &yys[YYMAXDEPTH] ) {
			  yyerror( "yacc stack overflow" );
			  return ( 1 );
		  }

		  *yyps = yystate;
		  ++yypv;
		  *yypv = yyval;

yynewstate:

		  yyn = yypact[yystate];

		  if ( yyn<= YYFLAG )
			  goto yydefault;    /* simple state */

		  if ( yychar < 0 )  {
			  if ( ( yychar = yylex() ) < 0 )
				  yychar=0;
		  }

		  if ( ( yyn += yychar ) < 0 || yyn >= YYLAST )
			  goto yydefault;

		  if ( yychk[ yyn = yyact[ yyn ] ] == yychar ) {
			  /* valid shift */
			  yychar  =  -1;
			  yyval   =  yylval;
			  yystate =  yyn;

			  if ( yyerrflag > 0 )
				  --yyerrflag;

			  goto yystack;
		  }

yydefault:
		  /* default state action */

		  if ( ( yyn = yydef[yystate]) == -2 ) {

					 if ( yychar < 0 )
						 if ( ( yychar = yylex() ) < 0 )
							 yychar = 0;
						 /* look through exception table */

					 for (
							 yyxi = yyexca;
							 ( *yyxi != (-1) ) || ( yyxi[1] != yystate ) ;
							 yyxi += 2
						  )
						  ; /* EMPTY_COMMAND */

					 while ( *( yyxi += 2 ) >= 0 )  {
							if ( *yyxi == yychar )
								break;
					 }

					 if ( ( yyn = yyxi[1] ) < 0 )
						 return ( 0 );   /* accept */
		  }

		  if ( yyn == 0 ) {    /* error */

					 /* error ... attempt to resume parsing */
					 switch ( yyerrflag )  {

						  case  0:   /* brand new error */

								yyerror( "syntax error" );
yyerrlab:
								++yynerrs;

						  case 1:
						  case 2:

								/* incompletely recovered error ... try again */

								yyerrflag = 3;

								/* find a state where "error"  */
								/* is a legal shift action     */

								while ( yyps >= yys ) {

									  yyn = yypact[*yyps] + YYERRCODE;

									  if (
											 yyn >= 0  &&
											 yyn < YYLAST &&
											 yychk[yyact[yyn]] == YYERRCODE
										  )   {
											/* simulate a shift of "error" */
											yystate = yyact[yyn];
											goto yystack;
									  }

									  yyn = yypact[*yyps];

									  /* the current yyps has no shift onn */
									  /* "error", pop stack */

									  if ( yydebug ) {
										  printf( "error recovery pops state %d, ",
													  *yyps);
										  printf( "uncovers %d\n", yyps[-1] );
										}

										--yyps;
										--yypv;
								}

								/* there is no state on the stack */
								/* with an error shift ... abort  */

yyabort:
								return(1);


						  case 3:
									/* no shift yet; clobber input char */

									if ( yydebug )
										printf( "error recovery discards char %d\n",
												  yychar );

									if ( yychar == 0 )
										/* don't discard EOF, quit */
                              goto yyabort;

                           yychar = -1;
                           /* try again in the same state */
                           goto yynewstate;

					 }  /* end_of_switch */

		  }  /* end_of_if */

        /* reduction by production yyn */

        if ( yydebug )
           printf( "reduce %d\n", yyn );

        yyps   -=  yyr2[yyn];
        yypvt   =  yypv;
        yypv   -=  yyr2[yyn];
        yyval   =  yypv[1];
		  yym     =  yyn;

        /* consult goto table to find next state */
        yyn     =  yyr1[yyn];
        yyj     =  yypgo[yyn]  +  *yyps + 1;

        if (
             yyj >= YYLAST ||
             yychk[ yystate = yyact[yyj] ] != -yyn
           )
           yystate = yyact[yypgo[yyn]];

        switch ( yym )  {

                        
case 2:
# line 64 "kcalc.y"
{ printResult(&yypvt[-0].attr); } break;
case 3:
# line 66 "kcalc.y"
{ quit = 1; } break;
case 4:
# line 70 "kcalc.y"
{ yyval.attr = yypvt[-0].attr; } break;
case 5:
# line 72 "kcalc.y"
{ if (yypvt[-2].attr.sig == 1)
            tmp2 = yypvt[-2].attr.ival;
          else if (yypvt[-2].attr.sig == 2)
            tmp2 = yypvt[-2].attr.dval;
          if (yypvt[-0].attr.sig == 1)
            ttmp2 = yypvt[-0].attr.ival;
          else if (yypvt[-0].attr.sig == 2)
            ttmp2 = yypvt[-0].attr.dval;
          yyval.attr.sig = 2;
          yyval.attr.dval = tmp2 + ttmp2;
          if (yyval.attr.dval == (double)((int)yyval.attr.dval)) {
            yyval.attr.sig = 1;
            yyval.attr.ival = (int)(tmp2+ttmp2);
          }
        } break;
case 6:
# line 88 "kcalc.y"
{ if (yypvt[-2].attr.sig == 1)
            tmp2 = yypvt[-2].attr.ival;
          else if (yypvt[-2].attr.sig == 2)
            tmp2 = yypvt[-2].attr.dval;
          if (yypvt[-0].attr.sig == 1)
            ttmp2 = yypvt[-0].attr.ival;
          else if (yypvt[-0].attr.sig == 2)
            ttmp2 = yypvt[-0].attr.dval;
          yyval.attr.sig = 2;
          yyval.attr.dval = tmp2 - ttmp2;
          if (yyval.attr.dval == (double)((int)yyval.attr.dval)) {
            yyval.attr.sig = 1;
            yyval.attr.ival = (int)(tmp2-ttmp2);
          }
        } break;
case 7:
# line 104 "kcalc.y"
{ if (yypvt[-2].attr.sig == 1)
            tmp2 = yypvt[-2].attr.ival;
          else if (yypvt[-2].attr.sig == 2)
            tmp2 = yypvt[-2].attr.dval;
          if (yypvt[-0].attr.sig == 1)
            ttmp2 = yypvt[-0].attr.ival;
          else if (yypvt[-0].attr.sig == 2)
            ttmp2 = yypvt[-0].attr.dval;
          yyval.attr.sig = 2;
          yyval.attr.dval = tmp2 * ttmp2;
          if (yyval.attr.dval == (double)((int)yyval.attr.dval)) {
            yyval.attr.sig = 1;
            yyval.attr.ival = (int)tmp2*ttmp2;
          }
        } break;
case 8:
# line 120 "kcalc.y"
{ if (yypvt[-2].attr.sig == 1)
            tmp2 = yypvt[-2].attr.ival;
          else if (yypvt[-2].attr.sig == 2)
            tmp2 = yypvt[-2].attr.dval;
          if (yypvt[-0].attr.sig == 1)
            ttmp2 = yypvt[-0].attr.ival;
          else if (yypvt[-0].attr.sig == 2)
            ttmp2 = yypvt[-0].attr.dval;
          yyval.attr.sig = 2;
          yyval.attr.dval = tmp2 / ttmp2;
          if (yyval.attr.dval == (double)((int)yyval.attr.dval)) {
            yyval.attr.sig = 1;
            yyval.attr.ival = (int)tmp2/ttmp2;
          }
        } break;
case 9:
# line 136 "kcalc.y"
{ if (yypvt[-2].attr.sig == 1)
            tmp2 = yypvt[-2].attr.ival;
          else if (yypvt[-2].attr.sig == 2)
            tmp2 = yypvt[-2].attr.dval;
          if (yypvt[-0].attr.sig == 1)
            ttmp2 = yypvt[-0].attr.ival;
          else if (yypvt[-0].attr.sig == 2)
            ttmp2 = yypvt[-0].attr.dval;
          yyval.attr.sig = 2;
          yyval.attr.dval = pow(tmp2,ttmp2);
        } break;
case 10:
# line 148 "kcalc.y"
{ if (yypvt[-2].attr.sig == 1)
            tmp = yypvt[-2].attr.ival;
          else if (yypvt[-2].attr.sig == 2)
            tmp = (int)yypvt[-2].attr.dval;
          if (yypvt[-0].attr.sig == 1)
            ttmp = yypvt[-0].attr.ival;
          else if (yypvt[-0].attr.sig == 2)
            ttmp = (int)yypvt[-0].attr.dval;
          yyval.attr.sig = 1;
          yyval.attr.ival = tmp % ttmp;
        } break;
case 11:
# line 160 "kcalc.y"
{ if (yypvt[-1].attr.sig == 1)
            tmp = yypvt[-1].attr.ival;
          else if (yypvt[-1].attr.sig == 2) {
            tmp = (int)yypvt[-1].attr.dval;
            fprintf(stdout, "Warning: Using decimal value as integer\n");
          }
          yyval.attr.sig = 1;
          yyval.attr.ival = (int)fact(tmp);
        } break;
case 12:
# line 170 "kcalc.y"
{ if (yypvt[-0].attr.sig == 1)
            tmp2 = yypvt[-0].attr.ival;
          else if (yypvt[-0].attr.sig == 2)
            tmp2 = yypvt[-0].attr.dval;
          yyval.attr.sig = 2;
          yyval.attr.dval = sin(tmp2);
        } break;
case 13:
# line 178 "kcalc.y"
{ if (yypvt[-0].attr.sig == 1)
            tmp2 = yypvt[-0].attr.ival;
          else if (yypvt[-0].attr.sig == 2)
            tmp2 = yypvt[-0].attr.dval;
          yyval.attr.sig = 2;
          yyval.attr.dval = cos(tmp2);
        } break;
case 14:
# line 186 "kcalc.y"
{ if (yypvt[-0].attr.sig == 1)
            tmp2 = yypvt[-0].attr.ival;
          else if (yypvt[-0].attr.sig == 2)
            tmp2 = yypvt[-0].attr.dval;
          yyval.attr.sig = 2;
          yyval.attr.dval = tan(tmp2);
        } break;
case 15:
# line 194 "kcalc.y"
{ if (yypvt[-0].attr.sig == 1)
            tmp2 = yypvt[-0].attr.ival;
          else if (yypvt[-0].attr.sig == 2)
            tmp2 = yypvt[-0].attr.dval;
          yyval.attr.sig = 2;
          ttmp2 = tan(tmp2);
          if (ttmp2 == 0)
            yyval.attr.dval = 0;
          else
            yyval.attr.dval = 1/ttmp2;
        } break;
case 16:
# line 206 "kcalc.y"
{ if (yypvt[-0].attr.sig == 1)
            tmp2 = yypvt[-0].attr.ival;
          else if (yypvt[-0].attr.sig == 2)
            tmp2 = yypvt[-0].attr.dval;
          yyval.attr.sig = 2;
          yyval.attr.dval = log10(tmp2);
        } break;
case 17:
# line 214 "kcalc.y"
{ if (yypvt[-0].attr.sig == 1)
            tmp2 = yypvt[-0].attr.ival;
          else if (yypvt[-0].attr.sig == 2)
            tmp2 = yypvt[-0].attr.dval;
          yyval.attr.sig = 2;
          yyval.attr.dval = log(tmp2)/log(2);
        } break;
case 18:
# line 222 "kcalc.y"
{ if (yypvt[-0].attr.sig == 1)
            tmp2 = yypvt[-0].attr.ival;
          else if (yypvt[-0].attr.sig == 2)
            tmp2 = yypvt[-0].attr.dval;
          yyval.attr.sig = 2;
          yyval.attr.dval = log(tmp2);
        } break;
case 19:
# line 230 "kcalc.y"
{ if (yypvt[-0].attr.sig == 1)
            tmp2 = yypvt[-0].attr.ival;
          else if (yypvt[-0].attr.sig == 2)
            tmp2 = yypvt[-0].attr.dval;
          yyval.attr.sig = 2;
          yyval.attr.dval = sqrt(tmp2);
        } break;
case 20:
# line 238 "kcalc.y"
{ if (yypvt[-0].attr.sig == 1)
            tmp2 = yypvt[-0].attr.ival;
          else if (yypvt[-0].attr.sig == 2)
            tmp2 = yypvt[-0].attr.dval;
          yyval.attr.sig = 1;
          yyval.attr.ival = (int)ceil(tmp2);
        } break;
case 21:
# line 246 "kcalc.y"
{ if (yypvt[-0].attr.sig == 1)
            tmp2 = yypvt[-0].attr.ival;
          else if (yypvt[-0].attr.sig == 2)
            tmp2 = yypvt[-0].attr.dval;
          yyval.attr.sig = 1;
          yyval.attr.ival = (int)floor(tmp2);
        } break;
case 22:
# line 254 "kcalc.y"
{ if (yypvt[-0].attr.sig == 1)
            yypvt[-0].attr.ival = -yypvt[-0].attr.ival;
          else if (yypvt[-0].attr.sig == 2)
            yypvt[-0].attr.dval = -yypvt[-0].attr.dval;
          yyval.attr = yypvt[-0].attr;
        } break;
case 23:
# line 261 "kcalc.y"
{ yyval.attr = yypvt[-0].attr; } break;
case 24:
# line 265 "kcalc.y"
{ tmp = findVAR(yypvt[-0].name,1);
            if (tmp != -1) {
              yyval.attr.sig = VARIABLES[tmp].attr.sig;
              yyval.attr.ival = VARIABLES[tmp].attr.ival;
              yyval.attr.dval = VARIABLES[tmp].attr.dval;

              if (yyval.attr.sig == 1)
                printf("[%s] = %d\n", yypvt[-0].name, yyval.attr.ival);
              else if (yyval.attr.sig == 2)
                printf("[%s] = %lf\n", yypvt[-0].name, yyval.attr.dval);
            } else {
              yyval.attr.sig = 1;
              yyval.attr.ival = 0;
            }
          } break;
case 25:
# line 281 "kcalc.y"
{ tmp = findVAR(yypvt[-2].name,0);
            if (tmp == -1)
              tmp = saveVAR(yypvt[-2].name,&yypvt[-0].attr);
            if (tmp != -1) {
              VARIABLES[tmp].attr.sig = yypvt[-0].attr.sig;
              VARIABLES[tmp].attr.ival = yypvt[-0].attr.ival;
              VARIABLES[tmp].attr.dval = yypvt[-0].attr.dval;

              yyval.attr.sig = yypvt[-0].attr.sig;
              yyval.attr.ival = yypvt[-0].attr.ival;
              yyval.attr.dval = yypvt[-0].attr.dval;

              if (yyval.attr.sig == 1)
                printf("let [%s] = %d\n", yypvt[-2].name, yyval.attr.ival);
              else if (yyval.attr.sig == 2)
                printf("let [%s] = %lf\n", yypvt[-2].name, yyval.attr.dval);
            }
          } break;
case 26:
# line 300 "kcalc.y"
{ yyval.attr = yypvt[-0].attr; } break;
case 27:
# line 302 "kcalc.y"
{ yyval.attr = yypvt[-1].attr; } break;
case 28:
# line 306 "kcalc.y"
{ yyval.attr.sig=1;
            yyval.attr.ival = yypvt[-0].attr.ival;
          } break;
case 29:
# line 310 "kcalc.y"
{ yyval.attr.sig=2;
            yyval.attr.dval = yypvt[-0].attr.dval;
          } break;
case 30:
# line 314 "kcalc.y"
{ yyval.attr.sig=2;
            yyval.attr.dval = 3.14159265358979323846264338327950288419716939937510;
          } break;
case 31:
# line 318 "kcalc.y"
{ yyval.attr.sig=2;
            yyval.attr.dval = 2.71828182845904523536028747135266249775724709369995;
          } break;

        }

        goto yystack;  /* stack new state and value */

}

