/*
 * MultiChatFrame.java
 *
 * Created on Nedeľa, 2008, január 27, 10:13
 */

package multichat;

import java.awt.event.KeyEvent;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.EventObject;
import javax.swing.AbstractListModel;
import javax.swing.text.BadLocationException;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import multichat.MultiChat.MessageListener;

/**
 *
 * @author  vbmacher
 */
public class MultiChatFrame extends javax.swing.JFrame {
    private MultiChat mc;
    private SimpleAttributeSet boldFont;
    private SimpleAttributeSet plainFont;
    private SimpleDateFormat sdf = new SimpleDateFormat("H:m:s");
    private WeirdListModel oModel;
    
    private class WeirdListModel extends AbstractListModel {
        private int size = 0;
        public void add() {
            size = mc.getOnlineList().length;
            fireContentsChanged(this, size, size);            
        }
        public void remove() {
            size = mc.getOnlineList().length;
            fireIntervalRemoved(this, size, size);
        }
        public int getSize() {
            return mc.getOnlineList().length;
        }
        public Object getElementAt(int index) {
            return mc.getOnlineList()[index];
        }
    }
    
    /**
     * draws message to glass..
     */
    public void drawMessage(String from, String data, long time) {
        try {
            txtHim.getStyledDocument().insertString(0, data + "\n", plainFont);
            txtHim.getStyledDocument().insertString(0, 
                    from + "(" + sdf.format(new Date(time)) + "):\n", boldFont);
        } catch (BadLocationException ex) {}
    }
    
    /** Creates new form MultiChatFrame */
    public MultiChatFrame() {
        initComponents();
        boldFont = new SimpleAttributeSet();
        plainFont = new SimpleAttributeSet();
        StyleConstants.setBold(boldFont,true);
        StyleConstants.setBold(plainFont,false);
        
        try {
            mc = new MultiChat(txtNick.getText());
            oModel = new WeirdListModel();
            onlineList.setModel(oModel);
            mc.addML(new MessageListener() {
                public void gotMessage(String from, String data, long time, EventObject e) {
                    drawMessage(from,data,time);
                }
                public void onlineChanged(boolean add) {
                    if (add) oModel.add();
                    else oModel.remove();
                }
            });
        } catch (IOException e) {}
        
        mainSplit.setDividerLocation(0.6);
        secondSplit.setDividerLocation(0.5);
        this.setLocationRelativeTo(null);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtNick = new javax.swing.JTextField();
        mainSplit = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        onlineList = new javax.swing.JList();
        secondSplit = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtMe = new javax.swing.JTextArea();
        sendToAllCheckbox = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtHim = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MultiChat");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                windowClosingHandler(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 14));
        jLabel2.setText("Tvoj nick:");

        txtNick.setText("newbie");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Kto je online:"));

        jScrollPane1.setViewportView(onlineList);

        mainSplit.setRightComponent(jScrollPane1);

        secondSplit.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pišeš ty:"));

        txtMe.setColumns(20);
        txtMe.setFont(txtMe.getFont().deriveFont((float)12));
        txtMe.setRows(5);
        txtMe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMeKeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(txtMe);

        sendToAllCheckbox.setText("Poslať všetkým");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(sendToAllCheckbox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(sendToAllCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE))
        );

        secondSplit.setRightComponent(jPanel1);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Piše on(a):"));

        txtHim.setEditable(false);
        txtHim.setFont(txtHim.getFont());
        jScrollPane2.setViewportView(txtHim);

        secondSplit.setLeftComponent(jScrollPane2);

        mainSplit.setLeftComponent(secondSplit);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNick, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(72, Short.MAX_VALUE))
            .addComponent(mainSplit, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainSplit, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void windowClosingHandler(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowClosingHandler
        mc.stop();
    }//GEN-LAST:event_windowClosingHandler

    private void txtMeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            evt.setKeyCode(0);
            if (onlineList.getSelectedIndex() == -1 && !sendToAllCheckbox.isSelected())
                return;
            String to_who = (String)onlineList.getSelectedValue();
            mc.send(to_who, txtMe.getText(), sendToAllCheckbox.isSelected());
            if (sendToAllCheckbox.isSelected() == false 
                    && (to_who == null || !to_who.equals(txtNick.getText()))) {
                drawMessage(txtNick.getText(), txtMe.getText(),
                        System.currentTimeMillis());
            }
            txtMe.setText("");
        }
}//GEN-LAST:event_txtMeKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        mc.change_nick(txtNick.getText());
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try { javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName()); }
                catch (javax.swing.UnsupportedLookAndFeelException e) {}
                catch (ClassNotFoundException e) {}
                catch (InstantiationException e) {}
                catch (IllegalAccessException e) {}
                new MultiChatFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane mainSplit;
    private javax.swing.JList onlineList;
    private javax.swing.JSplitPane secondSplit;
    private javax.swing.JCheckBox sendToAllCheckbox;
    private javax.swing.JTextPane txtHim;
    private javax.swing.JTextArea txtMe;
    private javax.swing.JTextField txtNick;
    // End of variables declaration//GEN-END:variables

}
