/*
 * AddEditSubtypeDialog.java
 *
 * Created on Utorok, 2008, jún 24, 10:21
 */

package oknatradika.gui;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import oknatradika.Main;
import oknatradika.gui.utils.NiceFileFilter;

/**
 *
 * @author  vbmacher
 */
public class AddEditSubtypeDialog extends javax.swing.JDialog {

    private ImageIcon picture;
    private boolean OOK = false;
    private String name;
    
    /** Creates new form AddEditSubtypeDialog */
    public AddEditSubtypeDialog(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        this.setTitle("Pridať nový podyp okna");
    }

    public AddEditSubtypeDialog(java.awt.Dialog parent, boolean modal,
            String name, ImageIcon picture) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        this.setTitle("Upraviť podyp okna");
        this.name = name;
        this.picture = picture;
        lblPicture.setIcon(picture);
        txtName.setText(name);
        lblPicture.revalidate();
        lblPicture.repaint();
    }
    
    public boolean getOK() { return OOK; }
    public String getSubtypeName() { return name; }
    public ImageIcon getImage() { return picture; }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnBrowse = new javax.swing.JButton();
        lblPicture = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Názov podtypu:");

        jLabel2.setText("Obrázok:");

        btnBrowse.setText("Prehľadávať...");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        lblPicture.setAutoscrolls(true);
        lblPicture.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPicture.setFocusable(false);

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBrowse)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)))
                    .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnBrowse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOK)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
    if (txtName.getText().equals("")) {
        Main.error("Názov podtypu nesmie byť prázdny !");
        txtName.grabFocus();
        return;
    }
    this.name = txtName.getText();
    this.picture = (ImageIcon) lblPicture.getIcon();
    this.OOK = true;
    dispose();
}//GEN-LAST:event_btnOKActionPerformed

private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
    JFileChooser f = new JFileChooser();
    NiceFileFilter f1 = new NiceFileFilter();
    NiceFileFilter f2 = new NiceFileFilter();

    f1.addExtension("jpg");
    f1.addExtension("bmp");
    f1.addExtension("gif");
    f1.addExtension("jpeg");
    f1.setDescription("Súbory obrázkov");
    f2.addExtension("*");
    f2.setDescription("Všetky súbory (*.*)");

    f.setDialogTitle("Otvoriť obrázok");
    f.setAcceptAllFileFilterUsed(false);
    f.addChoosableFileFilter(f1);
    f.addChoosableFileFilter(f2);
    f.setFileFilter(f1);
    f.setApproveButtonText("Otvoriť");

    int returnVal = f.showOpenDialog(this);
    f.setVisible(true);
    if (returnVal != JFileChooser.APPROVE_OPTION) return;
    
    picture = new ImageIcon(f.getSelectedFile().getAbsolutePath());
    lblPicture.setIcon(picture);
}//GEN-LAST:event_btnBrowseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblPicture;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

}
