/*
 * AddEditWindow.java
 *
 * Created on Piatok, 2008, jún 20, 8:05
 */

package oknatradika.gui;

import javax.swing.SpinnerNumberModel;
import oknatradika.Input;
import oknatradika.Main;
import oknatradika.data.WindowSubtype;
import oknatradika.data.WindowType;
import oknatradika.gui.utils.WSubtypeComboModel;
import oknatradika.gui.utils.WTypeComboModel;

/**
 *
 * @author  vbmacher
 */
public class AddEditWindow extends javax.swing.JDialog {

    private Input window;
    private boolean OOK = false;
    
    private WTypeComboModel type_model;
    private WSubtypeComboModel subtype_model;
    
    /** Creates new form AddEditWindow */
    public AddEditWindow(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        this.loadTypes();
        this.setTitle("Pridať nové okno");
    }
    
    public void enableItems() {
        if (chkSpojovaciProfil.isSelected()) {
            chkOwnLength.setEnabled(true);
            chkSpojDPH.setEnabled(true);
            if (chkOwnLength.isSelected())
                txtSpojLength.setEnabled(true);
            else
                txtSpojLength.setEnabled(false);
        } else {
            chkOwnLength.setEnabled(false);
            txtSpojLength.setEnabled(false);
            chkSpojDPH.setEnabled(false);
        }
    }
    
    public AddEditWindow(java.awt.Frame parent, boolean modal, Input win) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        this.loadTypes();
        this.setTitle("Upraviť okno");
        this.txtHeight.setText(String.valueOf(win.getVyska()));
        this.txtWidth.setText(String.valueOf(win.getSirka()));
        chkVonkajsiaP.setSelected(win.getVON());
        chkVnutornaP.setSelected(win.getVNU());
        chkVonDPH.setSelected(win.getDphVON());
        chkVnuDPH.setSelected(win.getDphVNU());
        chkMontaz.setSelected(win.getMON());
        chkZaluzie.setSelected(win.getZAL());
        chkVyspravky.setSelected(win.getVYS());
        chkSietky.setSelected(win.getSIE());
        chkZalDPH.setSelected(win.getDphZAL());
        chkMonDPH.setSelected(win.getDphMON());
        chkVysDPH.setSelected(win.getDphVYS());
        chkSieDPH.setSelected(win.getDphSIE());
        chkOknoDPH.setSelected(win.getDphOKN());
        txtZlava.setText(String.valueOf(win.getZlava()));
        txtKoeficient.setText(String.valueOf(win.getKoeficient()));

        chkSpojovaciProfil.setSelected(win.getSPOJ());
        chkSpojDPH.setSelected(win.getDphSPOJ());
        chkOwnLength.setSelected(win.getOwnLength());
        if (chkOwnLength.isSelected())
            txtSpojLength.setText(String.valueOf(win.getSpojLength()));
        enableItems();
        
        type_model.selectAtId(win.getTyp().getID());
        WindowSubtype[] wst = WindowSubtype.getAllSubtypes(win.getTyp().getID());
        subtype_model = new WSubtypeComboModel(wst);
        cmbPodtyp.setModel(subtype_model);
        subtype_model.selectAtId(win.getPodtyp().getID());

        WindowSubtype w = win.getPodtyp();
        if (w.getPicture() != null)
            lblPicture.setIcon(w.getPicture());
        else
            lblPicture.setIcon(null);

        cmbTyp.revalidate();
        cmbTyp.repaint();
        cmbPodtyp.revalidate();
        cmbPodtyp.repaint();
        spnCount.getModel().setValue(win.getKusov());
    }
    

    public boolean getOK() { return OOK;}
    public Input getWindow() { return window; }
    
    private void loadTypes() {
        WindowType[] wt = WindowType.getAllTypes();
        this.type_model = new WTypeComboModel(wt);
        this.subtype_model = new WSubtypeComboModel(null);

        this.cmbTyp.setModel(type_model);
        this.cmbPodtyp.setModel(subtype_model);
        cmbTyp.revalidate();
        cmbTyp.repaint();
        cmbPodtyp.revalidate();
        cmbPodtyp.repaint();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtHeight = new javax.swing.JTextField();
        txtWidth = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        chkMontaz = new javax.swing.JCheckBox();
        chkVyspravky = new javax.swing.JCheckBox();
        chkSietky = new javax.swing.JCheckBox();
        chkZaluzie = new javax.swing.JCheckBox();
        chkZalDPH = new javax.swing.JCheckBox();
        chkSieDPH = new javax.swing.JCheckBox();
        chkVysDPH = new javax.swing.JCheckBox();
        chkMonDPH = new javax.swing.JCheckBox();
        chkVonkajsiaP = new javax.swing.JCheckBox();
        chkVnutornaP = new javax.swing.JCheckBox();
        chkVnuDPH = new javax.swing.JCheckBox();
        chkVonDPH = new javax.swing.JCheckBox();
        chkSpojovaciProfil = new javax.swing.JCheckBox();
        chkOwnLength = new javax.swing.JCheckBox();
        txtSpojLength = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtZlava = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtKoeficient = new javax.swing.JTextField();
        chkOknoDPH = new javax.swing.JCheckBox();
        chkSpojDPH = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cmbTyp = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        cmbPodtyp = new javax.swing.JComboBox();
        lblPicture = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        spnCount = new javax.swing.JSpinner();
        btnVypocet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Okná Tradika");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Rozmery okna"));

        jLabel1.setFont(jLabel1.getFont());
        jLabel1.setText("Šírka okna:");

        jLabel2.setFont(jLabel2.getFont());
        jLabel2.setText("Výška okna:");

        txtHeight.setText("0");
        txtHeight.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtHeightFocusGained(evt);
            }
        });

        txtWidth.setText("0");
        txtWidth.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtWidthFocusGained(evt);
            }
        });

        jLabel3.setFont(jLabel3.getFont().deriveFont(jLabel3.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel3.setText("mm");

        jLabel4.setFont(jLabel4.getFont().deriveFont(jLabel4.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel4.setText("mm");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtHeight)
                    .addComponent(txtWidth, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Možnosti"));

        chkMontaz.setFont(chkMontaz.getFont());
        chkMontaz.setText("Montáž");

        chkVyspravky.setFont(chkVyspravky.getFont());
        chkVyspravky.setText("Vysprávky");

        chkSietky.setFont(chkSietky.getFont());
        chkSietky.setText("Sieťky proti hmyzu");

        chkZaluzie.setFont(chkZaluzie.getFont());
        chkZaluzie.setSelected(true);
        chkZaluzie.setText("Žalúzie");

        chkZalDPH.setFont(chkZalDPH.getFont());
        chkZalDPH.setText("DPH");

        chkSieDPH.setFont(chkSieDPH.getFont());
        chkSieDPH.setText("DPH");

        chkVysDPH.setFont(chkVysDPH.getFont());
        chkVysDPH.setText("DPH");

        chkMonDPH.setFont(chkMonDPH.getFont());
        chkMonDPH.setText("DPH");

        chkVonkajsiaP.setFont(chkVonkajsiaP.getFont());
        chkVonkajsiaP.setSelected(true);
        chkVonkajsiaP.setText("Vonkajšia parapeta");

        chkVnutornaP.setFont(chkVnutornaP.getFont());
        chkVnutornaP.setSelected(true);
        chkVnutornaP.setText("Vnútorná parapeta");

        chkVnuDPH.setFont(chkVnuDPH.getFont());
        chkVnuDPH.setText("DPH");

        chkVonDPH.setFont(chkVonDPH.getFont());
        chkVonDPH.setText("DPH");

        chkSpojovaciProfil.setFont(chkSpojovaciProfil.getFont());
        chkSpojovaciProfil.setText("Spojovací profil");
        chkSpojovaciProfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSpojovaciProfilActionPerformed(evt);
            }
        });

        chkOwnLength.setFont(chkOwnLength.getFont());
        chkOwnLength.setText("Vlastná dĺžka:");
        chkOwnLength.setEnabled(false);
        chkOwnLength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkOwnLengthActionPerformed(evt);
            }
        });

        txtSpojLength.setText("0");
        txtSpojLength.setEnabled(false);
        txtSpojLength.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSpojLengthFocusGained(evt);
            }
        });

        jLabel11.setFont(jLabel11.getFont().deriveFont(jLabel11.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel11.setText("mm");

        jLabel7.setText("Zľava na okno:");

        txtZlava.setText("0");
        txtZlava.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtZlavaFocusGained(evt);
            }
        });

        jLabel8.setFont(jLabel8.getFont().deriveFont(jLabel8.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel8.setText("%");

        jLabel9.setFont(jLabel9.getFont());
        jLabel9.setText("Koeficiet ceny:");

        txtKoeficient.setFont(txtKoeficient.getFont());
        txtKoeficient.setText("10");
        txtKoeficient.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtKoeficientFocusGained(evt);
            }
        });

        chkOknoDPH.setSelected(true);
        chkOknoDPH.setText("počítať DPH okna");

        chkSpojDPH.setText("počítať DPH");
        chkSpojDPH.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkSietky)
                                    .addComponent(chkVyspravky)
                                    .addComponent(chkMontaz)
                                    .addComponent(chkZaluzie)
                                    .addComponent(chkVonkajsiaP)
                                    .addComponent(chkVnutornaP))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkVnuDPH)
                                    .addComponent(chkVonDPH)
                                    .addComponent(chkZalDPH)
                                    .addComponent(chkVysDPH)
                                    .addComponent(chkSieDPH)
                                    .addComponent(chkMonDPH)))
                            .addComponent(chkSpojovaciProfil)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chkSpojDPH)
                                            .addComponent(chkOwnLength))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtZlava, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtSpojLength, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11))
                                    .addComponent(txtKoeficient, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(chkOknoDPH)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkVnutornaP)
                    .addComponent(chkVnuDPH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkVonkajsiaP)
                    .addComponent(chkVonDPH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkZaluzie)
                    .addComponent(chkZalDPH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkMontaz)
                    .addComponent(chkMonDPH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkVyspravky)
                    .addComponent(chkVysDPH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkSietky)
                    .addComponent(chkSieDPH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkSpojovaciProfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkOwnLength)
                    .addComponent(jLabel11)
                    .addComponent(txtSpojLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkSpojDPH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtZlava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtKoeficient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkOknoDPH)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Typ okna"));

        jLabel5.setFont(jLabel5.getFont());
        jLabel5.setText("Vyberte typ okna:");

        cmbTyp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTypActionPerformed(evt);
            }
        });

        jLabel6.setFont(jLabel6.getFont());
        jLabel6.setText("Vyberte podtyp okna:");

        cmbPodtyp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPodtypActionPerformed(evt);
            }
        });

        lblPicture.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setFont(jLabel10.getFont());
        jLabel10.setText("Počet kusov:");

        spnCount.setModel(new SpinnerNumberModel(1, 1, 99999, 1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPicture, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbTyp, 0, 249, Short.MAX_VALUE)
                            .addComponent(cmbPodtyp, 0, 249, Short.MAX_VALUE)
                            .addComponent(spnCount, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbTyp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbPodtyp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(spnCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPicture, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnVypocet.setFont(btnVypocet.getFont().deriveFont(btnVypocet.getFont().getStyle() | java.awt.Font.BOLD));
        btnVypocet.setText("OK - výpočet");
        btnVypocet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVypocetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnVypocet, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVypocet)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnVypocetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVypocetActionPerformed
    int width = 0;
    int height = 0;
    int zlava = 0;
    int kusov = 0;
    float koef = 0;
    int spojLength = 0;
    try { width = Integer.parseInt(txtWidth.getText()); }
    catch(Exception e) {
        Main.error("Neplatná šírka okna. Použite celé čísla");
        txtWidth.grabFocus();
        return;
    }
    try { height = Integer.parseInt(txtHeight.getText()); }
    catch(Exception e) {
        Main.error("Neplatná výška okna. Použite celé čísla");
        txtHeight.grabFocus();
        return;
    }
    try { zlava = Integer.parseInt(txtZlava.getText()); }
    catch(Exception e) {
        Main.error("Neplatná zľava. Použite celé čísla");
        txtZlava.grabFocus();
        return;
    }
    try { koef = Float.parseFloat(txtKoeficient.getText()); }
    catch (Exception e) {
        Main.error("Neplatný koeficient ceny okna. Použite desatinné čísla");
        txtKoeficient.grabFocus();
        return;
    }
    try { kusov = Integer.parseInt(spnCount.getModel().getValue().toString()); }
    catch(Exception e) {
        Main.error("Neplatný počet kusov okna. Použite celé čísla");
        spnCount.grabFocus();
        return;        
    }
    try { spojLength = Integer.parseInt(txtSpojLength.getText()); }
    catch(Exception e) {
        Main.error("Neplatná dĺžka spojovacieho profilu. Použite celé čísla");
        txtSpojLength.grabFocus();
        return;        
    }
        
    window = new Input(width, height, zlava, koef, chkVonkajsiaP.isSelected(),
            chkVnutornaP.isSelected(), chkZaluzie.isSelected(), 
            chkMontaz.isSelected(), chkVyspravky.isSelected(), 
            chkSietky.isSelected(), chkVonDPH.isSelected(),
            chkVnuDPH.isSelected(), chkZalDPH.isSelected(),
            chkMonDPH.isSelected(), chkVysDPH.isSelected(),
            chkSieDPH.isSelected(), chkOknoDPH.isSelected(), 
            new WindowType(type_model.getIdAt(cmbTyp.getSelectedIndex())),
            new WindowSubtype(subtype_model.getIdAt(cmbPodtyp.getSelectedIndex())),
            kusov, chkSpojovaciProfil.isSelected(),
            chkOwnLength.isSelected() ? spojLength : height, 
            chkSpojDPH.isSelected(), chkOwnLength.isSelected());
    OOK = true;
    dispose();
}//GEN-LAST:event_btnVypocetActionPerformed

private void cmbTypActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTypActionPerformed
    if (cmbTyp.getSelectedIndex() != -1) {
        try {
            WindowSubtype[] wst = WindowSubtype.getAllSubtypes(
                    ((WTypeComboModel)cmbTyp.getModel())
                    .getIdAt(cmbTyp.getSelectedIndex()));
            subtype_model = new WSubtypeComboModel(wst);
            cmbPodtyp.setModel(subtype_model);
            cmbPodtyp.revalidate();
            cmbPodtyp.repaint();
        } catch (Exception e) {}
    }
}//GEN-LAST:event_cmbTypActionPerformed

private void cmbPodtypActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPodtypActionPerformed
    if (cmbPodtyp.getSelectedIndex() != -1) {
        WindowSubtype w = subtype_model.getAt(cmbPodtyp.getSelectedIndex());
        if (w.getPicture() != null)
            lblPicture.setIcon(w.getPicture());
        else
            lblPicture.setIcon(null);
    }
}//GEN-LAST:event_cmbPodtypActionPerformed

private void txtWidthFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtWidthFocusGained
    txtWidth.setSelectionStart(0);
    txtWidth.setSelectionEnd(txtWidth.getText().length());
}//GEN-LAST:event_txtWidthFocusGained

private void txtHeightFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHeightFocusGained
    txtHeight.setSelectionStart(0);
    txtHeight.setSelectionEnd(txtHeight.getText().length());
}//GEN-LAST:event_txtHeightFocusGained

private void txtZlavaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtZlavaFocusGained
    txtZlava.setSelectionStart(0);
    txtZlava.setSelectionEnd(txtZlava.getText().length());
}//GEN-LAST:event_txtZlavaFocusGained

private void txtKoeficientFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtKoeficientFocusGained
    txtKoeficient.setSelectionStart(0);
    txtKoeficient.setSelectionEnd(txtKoeficient.getText().length());
}//GEN-LAST:event_txtKoeficientFocusGained

private void chkSpojovaciProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSpojovaciProfilActionPerformed
    enableItems();
}//GEN-LAST:event_chkSpojovaciProfilActionPerformed

private void chkOwnLengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkOwnLengthActionPerformed
    if (chkOwnLength.isSelected())
        txtSpojLength.setEnabled(true);
    else
        txtSpojLength.setEnabled(false);
}//GEN-LAST:event_chkOwnLengthActionPerformed

private void txtSpojLengthFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSpojLengthFocusGained
    txtSpojLength.setSelectionStart(0);
    txtSpojLength.setSelectionEnd(txtSpojLength.getText().length());
}//GEN-LAST:event_txtSpojLengthFocusGained

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVypocet;
    private javax.swing.JCheckBox chkMonDPH;
    private javax.swing.JCheckBox chkMontaz;
    private javax.swing.JCheckBox chkOknoDPH;
    private javax.swing.JCheckBox chkOwnLength;
    private javax.swing.JCheckBox chkSieDPH;
    private javax.swing.JCheckBox chkSietky;
    private javax.swing.JCheckBox chkSpojDPH;
    private javax.swing.JCheckBox chkSpojovaciProfil;
    private javax.swing.JCheckBox chkVnuDPH;
    private javax.swing.JCheckBox chkVnutornaP;
    private javax.swing.JCheckBox chkVonDPH;
    private javax.swing.JCheckBox chkVonkajsiaP;
    private javax.swing.JCheckBox chkVysDPH;
    private javax.swing.JCheckBox chkVyspravky;
    private javax.swing.JCheckBox chkZalDPH;
    private javax.swing.JCheckBox chkZaluzie;
    private javax.swing.JComboBox cmbPodtyp;
    private javax.swing.JComboBox cmbTyp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPicture;
    private javax.swing.JSpinner spnCount;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtKoeficient;
    private javax.swing.JTextField txtSpojLength;
    private javax.swing.JTextField txtWidth;
    private javax.swing.JTextField txtZlava;
    // End of variables declaration//GEN-END:variables

}
