/*
 * CatalogueDialog.java
 *
 * Created on Utorok, 2008, jún 24, 8:39
 */

package oknatradika.gui;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import oknatradika.Main;
import oknatradika.data.DerbyHandler;
import oknatradika.data.Window;
import oknatradika.data.WindowSubtype;
import oknatradika.data.WindowType;
import oknatradika.gui.utils.NiceFileFilter;
import oknatradika.gui.utils.SubtypesTableModel;
import oknatradika.gui.utils.WTypeComboModel;

/**
 *
 * @author  vbmacher
 */
public class CatalogueDialog extends javax.swing.JDialog {
    private SubtypesTableModel stm;
    private WTypeComboModel wcm;
    
    /** Creates new form CatalogueDialog */
    public CatalogueDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        stm = new SubtypesTableModel(null);
        tblPodtyp.setModel(stm);
        tblPodtyp.setRowHeight(200);
        wcm = new WTypeComboModel(WindowType.getAllTypes());
        cmbTyp.setModel(wcm);
        cmbTyp.setSelectedIndex(-1);
        countWindows();
    }

    private void countWindows() {
        try {
            DerbyHandler db = DerbyHandler.getInstance();
            ResultSet rs = db.query("select id from Windows");
            int i = 0;
            
            while(rs.next()) i++;
            lblWindowCount.setText(String.valueOf(i));
        } catch(SQLException e) {}
        
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbTyp = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPodtyp = new javax.swing.JTable();
        btnDeleteType = new javax.swing.JButton();
        btnEditType = new javax.swing.JButton();
        btnNewType = new javax.swing.JButton();
        btnDeleteSubtype = new javax.swing.JButton();
        btnEditSubtype = new javax.swing.JButton();
        btnNewSubtype = new javax.swing.JButton();
        btnSizeAndPrize = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblWindowCount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Katalóg okien");

        cmbTyp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTypActionPerformed(evt);
            }
        });

        jLabel1.setText("Základný typ okna:");

        tblPodtyp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblPodtyp);

        btnDeleteType.setText("Zmazať typ");
        btnDeleteType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteTypeActionPerformed(evt);
            }
        });

        btnEditType.setText("Upraviť typ");
        btnEditType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditTypeActionPerformed(evt);
            }
        });

        btnNewType.setText("Pridať typ");
        btnNewType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewTypeActionPerformed(evt);
            }
        });

        btnDeleteSubtype.setText("Zmazať podtyp");
        btnDeleteSubtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSubtypeActionPerformed(evt);
            }
        });

        btnEditSubtype.setText("Upraviť podtyp");
        btnEditSubtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditSubtypeActionPerformed(evt);
            }
        });

        btnNewSubtype.setText("Nový podtyp");
        btnNewSubtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewSubtypeActionPerformed(evt);
            }
        });

        btnSizeAndPrize.setText("Importovať okná");
        btnSizeAndPrize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSizeAndPrizeActionPerformed(evt);
            }
        });

        btnDelete.setText("Zmazať okná");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel2.setFont(jLabel2.getFont());
        jLabel2.setText("Počet všetkých okien spolu:");

        lblWindowCount.setFont(lblWindowCount.getFont().deriveFont(lblWindowCount.getFont().getStyle() | java.awt.Font.BOLD));
        lblWindowCount.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTyp, 0, 495, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnNewType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteType))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSizeAndPrize)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNewSubtype)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditSubtype)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteSubtype))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblWindowCount)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbTyp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteType)
                    .addComponent(btnEditType)
                    .addComponent(btnNewType))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblWindowCount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteSubtype)
                    .addComponent(btnEditSubtype)
                    .addComponent(btnNewSubtype)
                    .addComponent(btnSizeAndPrize)
                    .addComponent(btnDelete))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void cmbTypActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTypActionPerformed
    if (cmbTyp.getSelectedIndex() != -1) {
        try {
            WindowSubtype[] wst = WindowSubtype.getAllSubtypes(
                    ((WTypeComboModel)cmbTyp.getModel())
                    .getIdAt(cmbTyp.getSelectedIndex()));
            stm.updateModel(wst);
        } catch (Exception e) {}
    }

}//GEN-LAST:event_cmbTypActionPerformed

private void btnNewTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewTypeActionPerformed
    AddEditTypeDialog ad = new AddEditTypeDialog(this,true);
    ad.setVisible(true);
    if (ad.getOK()) {
        if (WindowType.addType(ad.getTypeName()) == false) {
            Main.error("Typ okna sa nepodarilo pridať do katalógu !");
        }
        this.wcm = new WTypeComboModel(WindowType.getAllTypes());
        cmbTyp.setModel(wcm);
        cmbTyp.revalidate();
        cmbTyp.repaint();
        countWindows();
    }    
}//GEN-LAST:event_btnNewTypeActionPerformed

private void btnEditTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditTypeActionPerformed
    int i =cmbTyp.getSelectedIndex();
    if (i == -1) {
        Main.error("Musí byť označený typ okna");
        cmbTyp.grabFocus();
        return;
    }
    AddEditTypeDialog ad = new AddEditTypeDialog(this,true,
            (String)cmbTyp.getSelectedItem());
    int id = wcm.getIdAt(i);
    ad.setVisible(true);
    if (ad.getOK()) {
        if (WindowType.editType(id, ad.getTypeName()) == 0)
            Main.error("Typ okna sa nepodarilo upraviť !");
        this.wcm = new WTypeComboModel(WindowType.getAllTypes());
        cmbTyp.setModel(wcm);
        cmbTyp.invalidate();
        cmbTyp.revalidate();
        cmbTyp.repaint();
        countWindows();
    }

}//GEN-LAST:event_btnEditTypeActionPerformed

private void btnDeleteTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteTypeActionPerformed
    int i = cmbTyp.getSelectedIndex();
    if (i == -1) {
        Main.error("Musí byť označený typ okna");
        cmbTyp.grabFocus();
        return;
    }
    if (JOptionPane.showConfirmDialog(this,
            "Naozaj chcete odstrániť typ okna zo zoznamu?"
            + "\n\nUPOZORNENIE: Týmto krokom odstránite všetky podtypy okien"
            + " tohto typu",
            "Potvrdenie", JOptionPane.YES_NO_OPTION)
            != JOptionPane.YES_OPTION)
        return;
    if (WindowType.deleteType(wcm.getIdAt(i)) == false)
        Main.error("Typ okna sa nepodarilo zmazať !");
    cmbTyp.setSelectedIndex(-1);
    this.wcm = new WTypeComboModel(WindowType.getAllTypes());
    cmbTyp.setModel(wcm);
    cmbTyp.invalidate();
    cmbTyp.revalidate();
    cmbTyp.repaint();
    countWindows();
}//GEN-LAST:event_btnDeleteTypeActionPerformed

private void btnNewSubtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewSubtypeActionPerformed
    int i = cmbTyp.getSelectedIndex();
    if (i == -1) {
        Main.error("Musí byť označený typ okna");
        cmbTyp.grabFocus();
        return;
    }
    int id = wcm.getIdAt(i); // id typu
    AddEditSubtypeDialog ad = new AddEditSubtypeDialog(this,true);
    ad.setVisible(true);
    if (ad.getOK()) {
        if (WindowSubtype.addSubtype(id,ad.getSubtypeName(), ad.getImage())
                == false) {
            Main.error("Podtyp okna sa nepodarilo pridať do katalógu !");
        }
        stm.updateModel(WindowSubtype.getAllSubtypes(id));
        countWindows();
    }
}//GEN-LAST:event_btnNewSubtypeActionPerformed

private void btnEditSubtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditSubtypeActionPerformed
    int i = cmbTyp.getSelectedIndex();
    if (i == -1) {
        Main.error("Musí byť označený typ okna !");
        cmbTyp.grabFocus();
        return;
    }
    int id = wcm.getIdAt(i); // id typu
    if (tblPodtyp.getSelectedRow() == -1) {
        Main.error("Musí byť označený podtyp okna !");
        tblPodtyp.grabFocus();
        return;
    }
    int subtyp_id = stm.getIdAt(tblPodtyp.getSelectedRow());
    
    WindowSubtype s = new WindowSubtype(subtyp_id);
    AddEditSubtypeDialog ad = new AddEditSubtypeDialog(this,true,
            s.getName(), s.getPicture());
    ad.setVisible(true);
    if (ad.getOK()) {
        if (WindowSubtype.editSubtype(subtyp_id, ad.getSubtypeName(),
                ad.getImage()) == 0) {
            Main.error("Podtyp okna sa nepodarilo pridať do katalógu !");
        }
        stm.updateModel(WindowSubtype.getAllSubtypes(id));
        countWindows();
    }
}//GEN-LAST:event_btnEditSubtypeActionPerformed

private void btnDeleteSubtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSubtypeActionPerformed
    int j = cmbTyp.getSelectedIndex();
    if (j == -1) {
        Main.error("Musí byť označený typ okna !");
        cmbTyp.grabFocus();
        return;
    }
    int id = wcm.getIdAt(j); // id typu

    int i = tblPodtyp.getSelectedRow();
    if (i == -1) {
        Main.error("Musí byť označený podtyp okna !");
        tblPodtyp.grabFocus();
        return;
    }
    if (JOptionPane.showConfirmDialog(this,
            "Naozaj chcete odstrániť podtyp okna zo zoznamu?"
             + "\n\nUPOZORNENIE: Týmto krokom odstránite všetky okná patriace"
             + " do označeného podtypu",
            "Potvrdenie", JOptionPane.YES_NO_OPTION)
            != JOptionPane.YES_OPTION)
        return;
    if (WindowSubtype.deleteSubtype(stm.getIdAt(i)) == false)
        Main.error("Typ okna sa nepodarilo zmazať !");
    stm.updateModel(WindowSubtype.getAllSubtypes(id));
    countWindows();
}//GEN-LAST:event_btnDeleteSubtypeActionPerformed

private void btnSizeAndPrizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSizeAndPrizeActionPerformed
    if (cmbTyp.getSelectedIndex() == -1) {
        Main.error("Musí byť označený typ okna !");
        cmbTyp.grabFocus();
        return;
    }
    int i = tblPodtyp.getSelectedRow();
    if (i == -1) {
        Main.error("Musí byť označený podtyp okna !");
        tblPodtyp.grabFocus();
        return;
    }
    JFileChooser f = new JFileChooser();
    NiceFileFilter f1 = new NiceFileFilter();
    NiceFileFilter f2 = new NiceFileFilter();

    f1.addExtension("csv");
    f1.setDescription("Súbory okien (*.csv)");
    f2.addExtension("*");
    f2.setDescription("Všetky súbory (*.*)");

    f.setDialogTitle("Importovať okná do vyznačeného podtypu");
    f.setAcceptAllFileFilterUsed(false);
    f.addChoosableFileFilter(f1);
    f.addChoosableFileFilter(f2);
    f.setFileFilter(f1);
    f.setApproveButtonText("Importovať");

    int returnVal = f.showOpenDialog(this);
    f.setVisible(true);
    if (returnVal != JFileChooser.APPROVE_OPTION) return;
    
    try {
        Window.importWindows(stm.getIdAt(i), f.getSelectedFile());
        countWindows();
    } catch (Exception e) {
        Main.error("Nepodarilo sa importovať okná !");
    }

}//GEN-LAST:event_btnSizeAndPrizeActionPerformed

private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
    if (cmbTyp.getSelectedIndex() == -1) {
        Main.error("Musí byť označený typ okna !");
        cmbTyp.grabFocus();
        return;
    }
    int i = tblPodtyp.getSelectedRow();
    if (i == -1) {
        Main.error("Musí byť označený podtyp okna !");
        tblPodtyp.grabFocus();
        return;
    }
    if (JOptionPane.showConfirmDialog(this,
            "Naozaj chcete zmazať všetky okná patriace do vybraného podtypu?",
            "Potvrdenie", JOptionPane.YES_NO_OPTION)
            != JOptionPane.YES_OPTION)
        return;
    Window.deleteWindows(stm.getIdAt(i));
    countWindows();
}//GEN-LAST:event_btnDeleteActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteSubtype;
    private javax.swing.JButton btnDeleteType;
    private javax.swing.JButton btnEditSubtype;
    private javax.swing.JButton btnEditType;
    private javax.swing.JButton btnNewSubtype;
    private javax.swing.JButton btnNewType;
    private javax.swing.JButton btnSizeAndPrize;
    private javax.swing.JComboBox cmbTyp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblWindowCount;
    private javax.swing.JTable tblPodtyp;
    // End of variables declaration//GEN-END:variables

}
