/*
 * MainWindow.java
 *
 * Created on Sobota, 2008, jún 21, 16:13
 */

package oknatradika.gui;

import java.awt.event.ActionEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import oknatradika.Calculation;
import oknatradika.Main;
import oknatradika.Report;
import oknatradika.gui.utils.WindowsTableModel;

/**
 *
 * @author  vbmacher
 */
public class MainWindow extends javax.swing.JFrame {

    private WindowsTableModel wtm;
    private ArrayList<Report> windows;
    
    
    /** Creates new form MainWindow */
    public MainWindow() {
        initComponents();
        wtm = new WindowsTableModel(null);
        windows = new ArrayList<Report>();
        tblWindows.setModel(wtm);
        tblWindows.setRowHeight(200);
        this.setLocationRelativeTo(null);
    }
    
    
    private void vypocetCelkom() {
        float suma = Calculation.getCenaCelkom(windows.toArray(new Report[0]));
        lblSuma.setText(String.format("%.2f EUR (%.2f Sk)", (float)(suma / 30.126), suma));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnNew = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnAddWindow = new javax.swing.JButton();
        btnEditWindow = new javax.swing.JButton();
        btnRemoveWindow = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnReport = new javax.swing.JButton();
        btnCatalogue = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnAbout = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblWindows = new javax.swing.JTable();
        jToolBar2 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        lblSuma = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Okná Tradika");

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/newz.gif"))); // NOI18N
        btnNew.setToolTipText("Nová zákazka");
        btnNew.setFocusable(false);
        btnNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNew);
        jToolBar1.add(jSeparator3);

        btnAddWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/new.gif"))); // NOI18N
        btnAddWindow.setToolTipText("Prdať nové okno");
        btnAddWindow.setFocusable(false);
        btnAddWindow.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddWindow.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddWindowActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAddWindow);

        btnEditWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/edit.gif"))); // NOI18N
        btnEditWindow.setToolTipText("Upraviť okno");
        btnEditWindow.setFocusable(false);
        btnEditWindow.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditWindow.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditWindowActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEditWindow);

        btnRemoveWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/delete.gif"))); // NOI18N
        btnRemoveWindow.setToolTipText("Odobrať okno");
        btnRemoveWindow.setFocusable(false);
        btnRemoveWindow.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRemoveWindow.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRemoveWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveWindowActionPerformed(evt);
            }
        });
        jToolBar1.add(btnRemoveWindow);
        jToolBar1.add(jSeparator1);

        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/report.gif"))); // NOI18N
        btnReport.setToolTipText("Vygenerovať správu");
        btnReport.setFocusable(false);
        btnReport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReport.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });
        jToolBar1.add(btnReport);

        btnCatalogue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/catalogue.gif"))); // NOI18N
        btnCatalogue.setToolTipText("Katalóg okien");
        btnCatalogue.setFocusable(false);
        btnCatalogue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCatalogue.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCatalogue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatalogueActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCatalogue);
        jToolBar1.add(jSeparator2);

        btnAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/about.gif"))); // NOI18N
        btnAbout.setToolTipText("O programe...");
        btnAbout.setFocusable(false);
        btnAbout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAbout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAbout);

        tblWindows.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblWindows.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblWindowsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblWindows);

        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        jLabel1.setFont(jLabel1.getFont());
        jLabel1.setText("Zákazka za: ");
        jToolBar2.add(jLabel1);

        lblSuma.setFont(lblSuma.getFont().deriveFont(lblSuma.getFont().getStyle() | java.awt.Font.BOLD));
        lblSuma.setText("0 Sk");
        jToolBar2.add(lblSuma);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
    new AboutDialog(this, true).setVisible(true);
}//GEN-LAST:event_btnAboutActionPerformed

private void btnAddWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddWindowActionPerformed
    AddEditWindow a = new AddEditWindow(this,true);
    a.setVisible(true);
    if (a.getOK() == true) {
        windows.add(Calculation.calculate(a.getWindow()));
        wtm.updateModel(windows.toArray(new Report[0]));
        vypocetCelkom();
      //  fileSaved = false;
      //  saveZakazka();
    }
}//GEN-LAST:event_btnAddWindowActionPerformed

private void btnEditWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditWindowActionPerformed
    if (tblWindows.getSelectedRow() == -1) {
        Main.error("Musí byť označené okno");
        return;
    }
    int i = tblWindows.getSelectedRow();
    AddEditWindow a = new AddEditWindow(this,true,
            windows.get(i).getInput());
    a.setVisible(true);
    if (a.getOK() == true) {
        windows.set(i, Calculation.calculate(a.getWindow()));
        wtm.updateModel(windows.toArray(new Report[0]));
        vypocetCelkom();
      //  fileSaved = false;
      //  saveZakazka();
    }
}//GEN-LAST:event_btnEditWindowActionPerformed

private void btnRemoveWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveWindowActionPerformed
    if (tblWindows.getSelectedRow() == -1) {
        Main.error("Musí byť označené okno");
        return;
    }
    int i = tblWindows.getSelectedRow();
    if (JOptionPane.showConfirmDialog(this,
            "Naozaj chcete odstrániť okno zo zoznamu?",
            "Potvrdenie", JOptionPane.YES_NO_OPTION) != JOptionPane.YES_OPTION) {
        return;
    }
    windows.remove(i);
    wtm.updateModel(windows.toArray(new Report[0]));
    vypocetCelkom();  
  //  fileSaved = false;
  //  saveZakazka();
}//GEN-LAST:event_btnRemoveWindowActionPerformed

private void tblWindowsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblWindowsMouseClicked
    if (evt.getClickCount() == 2) {
        btnEditWindowActionPerformed(new ActionEvent(this,0,""));
    }
}//GEN-LAST:event_tblWindowsMouseClicked

private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        new ReportDialog(this,true, 
                windows.toArray(new Report[0])).setVisible(true);
}//GEN-LAST:event_btnReportActionPerformed

private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
  //  if ((!fileSaved) && (JOptionPane.showConfirmDialog(this,
  //          "Terajšia zákazka nie je uložená. Naozaj chcete vytvoriť novú ?",
    //        "Potvrdenie", JOptionPane.YES_NO_OPTION)
      //      != JOptionPane.YES_OPTION))
        //return;
    windows.clear();
    wtm.updateModel(windows.toArray(new Report[0]));
    vypocetCelkom();
 //   fileSaved = true;
}//GEN-LAST:event_btnNewActionPerformed

private void btnCatalogueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatalogueActionPerformed
    new CatalogueDialog(this,true).setVisible(true);
}//GEN-LAST:event_btnCatalogueActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnAddWindow;
    private javax.swing.JButton btnCatalogue;
    private javax.swing.JButton btnEditWindow;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnRemoveWindow;
    private javax.swing.JButton btnReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JLabel lblSuma;
    private javax.swing.JTable tblWindows;
    // End of variables declaration//GEN-END:variables

}
