/*
 * ReportDialog.java
 *
 * Created on Piatok, 2008, jún 20, 9:11
 */

package oknatradika.gui;


import java.awt.Toolkit;
import java.io.File;
import java.io.StringReader;
import javax.swing.JFileChooser;
import javax.swing.text.Document;
import javax.swing.text.html.HTMLEditorKit;
import oknatradika.Main;
import oknatradika.Report;
import oknatradika.gui.utils.NiceFileFilter;
import java.awt.datatransfer.StringSelection;
import oknatradika.ReportManipulation;

/**
 *
 * @author  vbmacher
 */
public class ReportDialog extends javax.swing.JDialog {
    private Report[] res;
    
    /** Creates new form ReportDialog */
    public ReportDialog(java.awt.Frame parent, boolean modal, Report[] res) {
        super(parent, modal);
        this.res = res;
        initComponents();
        this.setLocationRelativeTo(parent);
        fillForm();
    }

    private void fillForm() {
        txtResults.setContentType("text/html");
        txtResults.setText("");
        insertHTML(ReportManipulation.generateHtml(res));
    }
    
    private void insertHTML(String html) {
        HTMLEditorKit kit = (HTMLEditorKit)txtResults.getEditorKit();
        Document doc = txtResults.getDocument();
        StringReader reader = new StringReader(html);
        try { kit.read(reader, doc, 0); } catch (Exception e) {}
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResults = new javax.swing.JEditorPane();
        btnSave = new javax.swing.JButton();
        btnCopy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Výsledky");

        jLabel1.setFont(jLabel1.getFont());
        jLabel1.setText("Nasledujúce výsledky môžete uložiť alebo skopírovať ako text.");

        txtResults.setContentType("text/html");
        jScrollPane1.setViewportView(txtResults);

        btnSave.setFont(btnSave.getFont());
        btnSave.setText("Uložiť ako...");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCopy.setFont(btnCopy.getFont());
        btnCopy.setText("Kopírovať");
        btnCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCopy)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(btnSave)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCopy))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopyActionPerformed
    try {
        String str = txtResults.getDocument().getText(0, 
                txtResults.getDocument().getLength());

        StringSelection s = new StringSelection(str);
        Toolkit.getDefaultToolkit().getSystemClipboard().setContents(s, s);
    } catch(Exception e) {}
}//GEN-LAST:event_btnCopyActionPerformed

    @SuppressWarnings("empty-statement")
private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
    JFileChooser f = new JFileChooser();
    NiceFileFilter f1 = new NiceFileFilter();
    NiceFileFilter f2 = new NiceFileFilter();
    NiceFileFilter f3 = new NiceFileFilter();
    NiceFileFilter f4 = new NiceFileFilter();

    f1.addExtension("rtf");
    f1.setDescription("Dokument RichText (*.rtf)");
    f2.addExtension("html");
    f2.setDescription("HTML stránka (*.html)");
    f3.addExtension("txt");
    f3.setDescription("Textový súbor (*.txt)");
    f4.addExtension("*");
    f4.setDescription("Všetky súbory (*.*)");

    f.setDialogTitle("Uložiť súbor");
    f.setAcceptAllFileFilterUsed(false);
    f.addChoosableFileFilter(f1);
    f.addChoosableFileFilter(f2);
    f.addChoosableFileFilter(f3);
    f.addChoosableFileFilter(f4);
    f.setFileFilter(f1);
    f.setApproveButtonText("Uložiť");

    int returnVal = f.showSaveDialog(this);
    f.setVisible(true);
    if (returnVal != JFileChooser.APPROVE_OPTION) return;
    
    File fileSource = f.getSelectedFile();
    if (!(fileSource.canWrite() == true || fileSource.exists() == false )) {
        Main.error("Nesprávny názov súboru");
        return;
    }
    String fn = fileSource.getAbsolutePath();
    NiceFileFilter fil = (NiceFileFilter)f.getFileFilter();
    if (fil.getExtension(fileSource) == null && fil.getFirstExtension()!=null) {
        if (!fil.getFirstExtension().equals("*"))
            fn +="."+fil.getFirstExtension();
    }
    fileSource = new java.io.File(fn);
    new WorkingDialog(this,true,fileSource,res,txtResults).setVisible(true);
}//GEN-LAST:event_btnSaveActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCopy;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JEditorPane txtResults;
    // End of variables declaration//GEN-END:variables

}
