/*
 * WorkingDialog.java
 *
 * Created on Streda, 2008, jún 25, 13:45
 */

package oknatradika.gui;

import java.io.File;
import javax.swing.JEditorPane;
import oknatradika.Report;
import oknatradika.ReportManipulation;

/**
 *
 * @author  vbmacher
 */
public class WorkingDialog extends javax.swing.JDialog {
    private WorkThread work;
            
    private class WorkThread extends Thread {
        private File fileS;
        private Report[] res;
        private JEditorPane txtResults;
        private WorkingDialog wd;
        
        public WorkThread(File fileS, Report[] res, JEditorPane txt,
                WorkingDialog wd) {
            this.fileS = fileS;
            this.res = res;
            this.txtResults = txt;
            this.wd = wd;
            this.start();
        }
        
        public void run() {
            ReportManipulation.saveFile(fileS, res, txtResults);
            wd.dispose();
        }
        
        public void stopRun() {
            ReportManipulation.shouldStop = true;
        }
    }
    
    /** Creates new form WorkingDialog */
    public WorkingDialog(java.awt.Dialog parent, boolean modal,
            final File fileS, final Report[] res, final JEditorPane txtResults) {
        super(parent, modal);
        initComponents();
    this.setLocationRelativeTo(parent);
    
        work = new WorkThread(fileS, res, txtResults,this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel1.setText("Pracujem, prosím čakajte...");

        btnCancel.setText("Zrušiť");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
    work.stopRun();
    this.dispose();
}//GEN-LAST:event_btnCancelActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
